import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "@mantine/core/styles.css"
import "./globals.css";
import React from "react";
import {MantineProvider} from "@mantine/core";
import {ModalsProvider} from '@mantine/modals';


const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
								children,
							}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
		<body className={inter.className}>
		<MantineProvider forceColorScheme={'dark'}>
			<ModalsProvider labels={{
				cancel: "Cancel",
				confirm: "Yes"
			}}>
				{children}
			</ModalsProvider>
		</MantineProvider>
		</body>
		</html>
	);
}

export const dynamic = 'force-dynamic'
